env:
  CIRRUS_CLONE_DEPTH: "1"
  GITHUB_TOKEN: "ENCRYPTED[75db4a3a95cd4858ff61d5de8bbab14abc02b739c03c6fbc54ee53228e8afe3467f5d5e9f1094532325321379d1863c9]"

arm64_task:
  name: ARM64 build
  timeout_in: 120m
  container:
    image: fedora:rawhide
    cpu: 8
    memory: 20G
  setup_env_script:
    - dnf -y upgrade
    - dnf -y groupinstall "Development tools"
    - dnf -y install binutils-devel bison clang cmake flex g++ glibc-devel glibc-devel.i686 gmp-devel libmpc-devel lld llvm llvm-devel mpfr-devel ninja-build tar texinfo which zlib-devel
    - chmod a+x ci.sh
  build_script:
    - env bash ci.sh --arm64

arm_task:
  name: ARM build
  timeout_in: 120m
  container:
    image: fedora:rawhide
    cpu: 8
    memory: 20G
  setup_env_script:
    - dnf -y upgrade
    - dnf -y groupinstall "Development tools"
    - dnf -y install binutils-devel bison clang cmake flex g++ glibc-devel glibc-devel.i686 gmp-devel libmpc-devel lld llvm llvm-devel mpfr-devel ninja-build tar texinfo which zlib-devel
    - chmod a+x ci.sh
  build_script:
    - env bash ci.sh --arm
